"""add last_seen_at

Revision ID: ac29dd64b628
Revises: 61441c129f0b
Create Date: 2026-06-07 21:17:12.771057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac29dd64b628'
down_revision: Union[str, Sequence[str], None] = '61441c129f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_projects_last_seen_at'), 'projects', ['last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_last_seen_at'), table_name='projects')
    op.drop_column('projects', 'last_seen_at')
    # ### end Alembic commands ###
